defaults:
  - model: model
  - dataset: data
  - server: server
  - _self_

params:
  beamWidth: 5  # How many beam to keep when decoder = 'beamsearch' or 'wordbeamsearch'
  min_size: 10  # Filter text box smaller than minimum value in pixel
  workers: 0
  contrast_ths: 0.1  # Text box with contrast lower than this value will be passed into model 2 times. First is with original image and second with contrast adjusted to 'adjust_contrast' value. The one with more confident level will be returned as a result.
  low_text: 0.4  # (float, default = 0.4) - Text low-bound score
  link_threshold: 0.4  #  (float, default = 0.4) - Link confidence threshold
  slope_ths: 0.1  # (float, default = 0.1) - Maximum slope (delta y/delta x) to considered merging. Low value means tiled boxes will not be merged.
  ycenter_ths: 0.5  # (float, default = 0.5) - Maximum shift in y direction. Boxes with different level should not be merged.
  height_ths: 0.5  # (float, default = 0.5) - Maximum different in box height. Boxes with very different text size should not be merged.
  width_ths: 0.5  # (

